const undergradClasses = [
  // F2018
  {
    dept: 'COM SCI',
    number: '1',
    name: 'Freshman CS Seminar',
    quarter: 'F',
    year: 2018,
  },
  {
    dept: 'COM SCI',
    number: '31',
    name: 'Intro to Computer Science 1',
    informal: 'Intro C++',
    quarter: 'F',
    year: 2018,
  },
  {
    dept: 'ENGCOMP',
    number: '3',
    name: 'English Composition - Rhetoric and Language',
    informal: 'English Comp',
    quarter: 'F',
    year: 2018,
  },
  {
    dept: 'MATH',
    number: '31A',
    name: 'Differential and Integral Calculus',
    informal: 'Single Variable Calc (1)',
    quarter: 'F',
    year: 2018,
  },
  // W2019
  {
    dept: 'COM SCI',
    number: '32',
    name: 'Intro to Computer Science 2',
    informal: 'Data Structures',
    quarter: 'W',
    year: 2019,
  },
  {
    dept: 'MATH',
    number: '31B',
    name: 'Integration and Infinite Series',
    informal: 'Single Variable Calc (2)',
    quarter: 'W',
    year: 2019,
  },
  {
    dept: 'MATH',
    number: '32A',
    name: 'Calculus of Several Variables',
    informal: 'Multivariable Calc (1)',
    quarter: 'W',
    year: 2019,
  },
  {
    dept: 'PHYSICS',
    number: '1A',
    name: 'Mechanics',
    quarter: 'W',
    year: 2019,
  },
  // S2019
  {
    dept: 'COM SCI',
    number: '33',
    name: 'Computer Organization',
    quarter: 'S',
    year: 2019,
  },
  {
    dept: 'COM SCI',
    number: '35L',
    name: 'Software Construction Lab',
    informal: 'Software Lab',
    quarter: 'S',
    year: 2019,
  },
  {
    dept: 'MATH',
    number: '33A',
    name: 'Linear Algebra and Applications',
    informal: 'Linear Algebra',
    quarter: 'S',
    year: 2019,
  },
  {
    dept: 'MATH',
    number: '61',
    name: 'Discrete Structures',
    informal: 'Discrete Math',
    quarter: 'S',
    year: 2019,
  },
  {
    dept: 'MECH&AE',
    number: '194',
    name: 'Research Group Seminar',
    informal: 'BEAM Pedagogy',
    quarter: 'S',
    year: 2019,
  },
  // F2019
  {
    dept: 'COM SCI',
    number: '180',
    name: 'Algorithms and Complexity',
    informal: 'Algorithms',
    quarter: 'F',
    year: 2019,
  },
  {
    dept: 'COM SCI',
    number: 'M51A',
    name: 'Logic Design - Digital Systems',
    informal: 'Logic Design',
    quarter: 'F',
    year: 2019,
  },
  {
    dept: 'ECON',
    number: '11',
    name: 'Microeconomic Theory',
    informal: 'Intermediate Econ',
    quarter: 'F',
    year: 2019,
  },
  {
    dept: 'MATH',
    number: '32B',
    name: 'Calculus of Several Variables',
    informal: 'Multivariable Calc (2)',
    quarter: 'F',
    year: 2019,
  },
  // W2020
  {
    dept: 'COM SCI',
    number: '131',
    name: 'Programming Languages',
    quarter: 'W',
    year: 2020,
  },
  {
    dept: 'ECON',
    number: '101',
    name: 'Microeconomic Theory',
    quarter: 'W',
    year: 2020,
  },
  {
    dept: 'MATH',
    number: '115A',
    name: 'Linear Algebra',
    informal: 'Linear Algebra',
    quarter: 'W',
    year: 2020,
  },
  {
    dept: 'MATH',
    number: '33B',
    name: 'Differential Equations',
    quarter: 'W',
    year: 2020,
  },
  {
    dept: 'PHYSICS',
    number: '4AL',
    name: 'Mechanics Lab',
    quarter: 'W',
    year: 2020,
  },
  // S2020
  {
    dept: 'COM SCI',
    number: '111',
    name: 'Operating Systems Principles',
    informal: 'Operating Systems',
    quarter: 'S',
    year: 2020,
    online: true,
  },
  {
    dept: 'COM SCI',
    number: '161',
    name: 'Artificial Intelligence',
    quarter: 'S',
    year: 2020,
    online: true,
  },
  {
    dept: 'COM SCI',
    number: 'M152A',
    name: 'Digital Design Lab',
    quarter: 'S',
    year: 2020,
    online: true,
  },
  {
    dept: 'ECON',
    number: '102',
    name: 'Macroeconomic Theory',
    quarter: 'S',
    year: 2020,
    online: true,
  },
  {
    dept: 'MATH',
    number: '131A',
    name: 'Analysis',
    informal: 'Real Analysis',
    quarter: 'S',
    year: 2020,
    online: true,
  },
  // U2020 (summer session)
];
