const undergradClasses = [
  // F2018
  {
    dept: 'COM SCI',
    number: "1",
    name: "Freshman CS Seminar",
    quarter: "F",
    year: 2018,
  },
  {
    dept: 'COM SCI',
    number: "31",
    name: "Intro to Computer Science 1",
    informal: "Intro C++",
    quarter: "F",
    year: 2018,
  },
  {
    dept: 'ENGCOMP',
    number: "3",
    name: "English Composition - Rhetoric and Language",
    informal: "English Comp",
    quarter: "F",
    year: 2018,
  },
  {
    dept: 'MATH',
    number: "31A",
    name: "Differential and Integral Calculus",
    informal: "Single Variable Calc (1)",
    quarter: "F",
    year: 2018,
  },
  // W2019
  {
    dept: 'COM SCI',
    number: "32",
    name: "Intro to Computer Science 2",
    informal: "Data Structures",
    quarter: "W",
    year: 2019,
  },
  {
    dept: 'MATH',
    number: "31B",
    name: "Integration and Infinite Series",
    informal: "Single Variable Calc (2)",
    quarter: "W",
    year: 2019,
  },
  {
    dept: 'MATH',
    number: "32A",
    name: "Calculus of Several Variables",
    informal: "Multivariable Calc (1)",
    quarter: "W",
    year: 2019,
  },
  {
    dept: 'PHYSICS',
    number: "1A",
    name: "Mechanics",
    quarter: "W",
    year: 2019,
  },
  // S2019
  {
    dept: 'COM SCI',
    number: "33",
    name: "Computer Organization",
    quarter: "S",
    year: 2019,
  },
  {
    dept: 'COM SCI',
    number: "35L",
    name: "Software Construction Lab",
    informal: "Software Lab",
    quarter: "S",
    year: 2019,
  },
  {
    dept: 'MATH',
    number: "33A",
    name: "Linear Algebra and Applications",
    informal: "Linear Algebra",
    quarter: "S",
    year: 2019,
  },
  {
    dept: 'MATH',
    number: "61",
    name: "Discrete Structures",
    informal: "Discrete Math",
    quarter: "S",
    year: 2019,
  },
  {
    dept: 'MECH&AE',
    number: "194",
    name: "Research Group Seminar",
    informal: "BEAM Pedagogy",
    quarter: "S",
    year: 2019,
  },
];
